### ISSUE TITLE
file pathSeparator

### ISSUE THREAD

**Issue by richardgist** [Bresiu/android-manifest-merger#1]
java -jar target/manifest-merger-jar-with-dependencies.jar --main <path_to_main_manifest> --libs <path_to_libs_manifests_divided by ':'> --out <output_manifest> --log WARNING

File.pathSeparator  is ';' not ':' in windows

**Comment by Bresiu** [comment]
@richardgist Manifest Merger was tested on OSX only. Thanks for letting me know.
